<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class ShopCartResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'subTotalPrice'=>(float)$this->sub_total_price+(.001),
            'subTotalPriceFormat'=>$this->sub_total_price_format,
            'totalTax'=>(float)$this->total_tax+(.001) ,
            'totalTaxFormat'=>$this->total_tax_format,
            'totalPriceFormat'=>$this->total_price_format,
            'totalPrice'=>(float)$this->total_price+(.001) ,
            'products'=>ShopCartListResource::collection($this->cart_list)
        ];
    }
}



class ShopCartListResource extends JsonResource{

    public function toArray($request)
    {
        return [
            'productId'=>$this->product_id,
            'vendorStockId'=>$this->vendorStockId,
            'img'=>$this->img,
            'name'=>$this->name,
            'quantity'=>$this->quantity,
            'campaign'=>$this->campaign,
            'campaignId'=>$this->campaign_id,
            'priceFormat'=>$this->price_format,
            'price'=>$this->price + (.00001),
            'subPrice'=>$this->sub_price + (.00001),
            'subPriceFormat'=>$this->sub_price_format,
            'shopName'=>$this->shop_name,
        ]; // TODO: Change the autogenerated stub
    }
}